image: node:latest

stages:
  - install
  - build
  - release
  - containerize

include:
  - remote: https://gitlab.com/TIBHannover/gitlab-ci-templates/raw/master/templates/Docker.gitlab-ci.yml

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next
    
release:
  stage: release
  only:
    - main
  script:
    - npm run semantic-release